# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0003_auto_20161011_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='image',
            field=models.FileField(blank='True', null='True', upload_to='images/passages'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank='True', null='True', upload_to='images/topics'),
        ),
    ]
