# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0004_auto_20161011_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartopic',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/passages'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Topic'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='vocabs',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Vocab'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='fulltext',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grammarTopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.GrammarTopic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.Passage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='translation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='typeOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='vocabs',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Vocab'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/topics'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.Level'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='otherForm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
