# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0005_auto_20161011_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/vocabs'),
        ),
    ]
