# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0006_vocab_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='otherForm',
            new_name='past_tense',
        ),
        migrations.AddField(
            model_name='vocab',
            name='pasticiple',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
