# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0010_useranswer_useranswergrammarquiz_uservocab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
