# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0012_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartopic',
            name='engtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
