# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 01:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0013_grammartopic_engtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartopic',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
