# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0014_auto_20161013_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='isTrue',
            new_name='istrue',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='isTestSix',
            new_name='istestsix',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='grammarTopics',
            new_name='grammartopics',
        ),
        migrations.RenameField(
            model_name='useranswergrammarquiz',
            old_name='grammarTopic',
            new_name='grammartopic',
        ),
    ]
