# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0015_auto_20161013_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grammartopics',
        ),
        migrations.RemoveField(
            model_name='useranswergrammarquiz',
            name='grammartopic',
        ),
    ]
