# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0016_auto_20161013_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grammartopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.GrammarTopic'),
        ),
        migrations.AddField(
            model_name='useranswergrammarquiz',
            name='grammartopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.GrammarTopic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='listeningtopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.ListeningTopic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
