# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0020_question_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grammartopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.GrammarTopic'),
        ),
    ]
