# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0021_question_grammartopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='session',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
