# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0022_useranswer_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='session',
        ),
    ]
