# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0025_auto_20161015_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/questions'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/vocabs'),
        ),
    ]
