# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0027_auto_20161016_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='phonetic',
            new_name='phonetica',
        ),
        migrations.AddField(
            model_name='vocab',
            name='phoneticb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
