# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0031_userdictation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='listeningtopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.ListeningTopic'),
        ),
        migrations.AddField(
            model_name='video',
            name='listeningtopics',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.ListeningTopic'),
        ),
    ]
