# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toeic', '0033_auto_20161018_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(blank=True, default=1, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AddField(
            model_name='passage',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Question'),
        ),
        migrations.AddField(
            model_name='video',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Question'),
        ),
        migrations.AddField(
            model_name='useranswervideo',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.Question'),
        ),
        migrations.AddField(
            model_name='useranswervideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswervideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.Video'),
        ),
    ]
