# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0034_auto_20161019_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
