# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0035_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id')},
        ),
    ]
