# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0036_auto_20161019_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswergrammarquiz',
            name='session',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='userdictation',
            name='session',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='uservocab',
            name='session',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
