# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0038_uservocab_typeoftest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='vocabs',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Vocab'),
        ),
    ]
