# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0039_dictation_vocabs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswerVideo',
            new_name='UserAnswerVideoLesson',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoLesson',
        ),
        migrations.RenameModel(
            old_name='VideoType',
            new_name='VideoLessonType',
        ),
    ]
