# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 02:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0040_auto_20161024_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronunciationLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('dictations', models.ManyToManyField(blank=True, null=True, to='toeic.Dictation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.Level')),
                ('videoType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.VideoLessonType')),
                ('vocabs', models.ManyToManyField(blank=True, null=True, to='toeic.Vocab')),
            ],
        ),
    ]
