# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 07:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0041_pronunciationlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='engdefinition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='definition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='main_form',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
