# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0042_auto_20161027_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='definition',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='main_form',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
