# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0045_auto_20161111_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakingquestion',
            old_name='speakingAnswer',
            new_name='speakinganswer',
        ),
    ]
