# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0047_auto_20161111_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingquestion',
            name='textwithblank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
