# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0048_speakingquestion_textwithblank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakinglesson',
            old_name='questionset',
            new_name='questions',
        ),
        migrations.RenameField(
            model_name='speakingpractice',
            old_name='practiceset',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='speakingpractice',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.SpeakingAnswer'),
        ),
    ]
