# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0049_auto_20161111_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakinglesson',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
