# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0050_auto_20161115_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingpractice',
            name='text',
        ),
        migrations.AddField(
            model_name='speakingpractice',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
