# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0051_auto_20161115_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspeakinganswer',
            old_name='exercise',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='speakingpracticetype',
            name='instruction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userspeakinganswer',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toeic.SpeakingPractice'),
        ),
    ]
