# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0053_auto_20161116_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinganswer',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='speakinganswer',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
