# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0054_auto_20161116_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinglesson',
            name='isfirst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speakinglesson',
            name='islast',
            field=models.BooleanField(default=False),
        ),
    ]
