# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0057_speakingquestion_audioa'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinganswer',
            name='audioa',
            field=models.FileField(blank=True, null=True, upload_to='audios/speakinganswer'),
        ),
    ]
