# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0058_speakinganswer_audioa'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinglesson',
            name='vocabs',
            field=models.ManyToManyField(blank=True, null=True, to='toeic.Vocab'),
        ),
    ]
