# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0059_speakinglesson_vocabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakinglesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
